language: scala
scala:
- 2.12.1
jdk:
- oraclejdk8
branches:
  only:
  - master
  - nc/52-docker-update
sudo: required
dist: precise
addons:
  postgresql: '9.5'
services:
  - postgresql
  - rabbitmq
script:
  - make image
env:
  global:
  - secure: srelRDzGDWfGFvoSMeNHtDESATsQbUS3Ci/JNSG6p6WDFhJPIvZF6ErMXTM+xor4U0l3tmpnu4iQ0roHiHo2UGW7gLBn39ughNetflZilgk6IfxK9BTKd453cjQKlBrFz+O+7SgurKdHRMhGqruKq9cyGAaG5pGVsqcTG3m6wEQsxMiTGzkxKY8KEzo2hRX6xqN1v9BRFE3cwSJgmyvekpNq9eibPw+mZ6iCaxZ31qSIRS3BXOQwLRZSEMPMbeIA+Pa6YF6bkCvMtCbsbquONH9MPsClaXZjtnG2aGQwUj4tG+/8cZbFRhtAHqEqynDi3P1tM5bzWCbjkgNcTDCQtUogbkq8OVQ1Z8nqxki2aWAfV9jtCxg+Rz4/rbJtZNHg17xGm+ubK6QvXL5ExZeJwqbUttCgrEPPsLLB/kuHFZkbOH2lyz0K0F+bTLjVNh+bDH/UjE14gdcO7866qBrFdp+OTlD1nAEZOG7nsRHbj90K1dY3EhiZts4i+YOshAg5HZTOVyCbZsNUR3GNoK5JmYhMiP0vWuXa2KHfDscsgh0SNrUfrElsADJycBf5vUYh/Yl5Bni5By1uycOugc4IZCbph0GfUb3PWYuXc+IKev4aNVSZYnfNdaazVUmJCOaFh1qDZaalHOBKW6iCdIS6rmVJDJmB3Ci/wF+kghl1t/Y=
  - secure: ZO7d/PSCd2iVHJwioXyOh9IfaNUXt8xVg4P4IqUve6CuRPuPOf9osIRTNxn5DyHPznJNVPxien/QBgxVLvA/VP/Nvgt7v0B8m2mwWNeG9y6VmerThFcvKFds6LPXd6Xiw9rFW6S4swDMX4SCDUmEa25/PVcoQxl5X7KgCkumgltdyCT1NlMObzkjJZmyhMZgMV5vtjndkSOEfjorfua/Hcc9n/gpdDhHviZ8eUZe21gsFthdnMixwIR8LlUe7Gjjy6L6bdU9zexvoY/b3NoVrw3Fg0VDs0DWdd4PXaOE60y1qywVqvzGzc3E7PGpHvWzCmHKjzK65HOaHGUEhI8o1twS3i2/0gekrB6Fgh/4Qc5ZSM1p+292jDf9cndDwdX3FtcimAM37MuzUfkk8JigDrTZjGpS9YmNLKs2fA3/mF+3sEyt1Yd4SJcgVPOJvhRmHow7kjbcXgj5QqFJDjC44lc5zBX44uQkaInp7BnddlT7gE3zcB+6nWumamNlIvao0uN1ECNQWz3C48XBrVxjAB0qWgpDfVvEC0GoX1G2mwFz+r0vmT0bKZqlpqe5e3L3jtgd5EmL7PmxYg1JY8ccU7bdP7A0hAO8jM5bmf3lW3Nv0/jTg6UAyvB+hZozQjL5nALipgsP9n8IEGKIopZaJ0FWGQt2OOs2f6aRRaiMoJo=
  - secure: dchCvye+rwc5+EePg1QEOtLE9cSC0jRHygfwRwIHqrpCUygg3qLTM3cMsKR2oOfH5KUKUBXVlnvYvuouZ22Yf/RDSoTDtD7N4iDNS6CKK0pSg8MCCEP3jEZ1A0GOlYz+mON/LHPP/GUFIFeYi7SrVdHIaCYKeIAaPhin8Nx9VHc3Ls/rdRrT+9887l4ECidC5deM05jIJHeK/pdVmPH7fSLvi+IsmSVHrUbd9wjIMezpYot+ayu/JnBm5Qy5s4TNlH3F4iSybO4oyJy8k1gGZ8U8PtGEl7XUOLQFTe7quKbvcEwlYnT6waPPwX4+HEaPSNDXBWmLjdGBS6B+9Nf/0e41xc+jt8+qf9XX3Lx3nq1O9Cdi17krXP+ktiKWPy2dpg+hQi+B6ZGgk14BK1VaH03XvaPasyVnPX6L59lhs19eGViM+Mtatuda1MbWe7A0Mv0FHZWYE7G+hI+22JjUNQqLjQsX/WauCRt4TA7pkSN4NutVJ36ZZBvkrfuEmcWmXjfHMgLhwT4ipOleO0zJAdJdNt5wBJCb+PWLbwCRVoFG+ewOWEd4FhOX3lNJD3ITPNPLTCflkYa6wYIYd9mxDEzZTZVsPnB7rFV4deRxEnZkswcs/VnDcMFAL9s5tjltkV56Wle3FGmUqluUGiOcm7n+w8bt+WwtF/QAR3ypPQg=
